### ISSUE TITLE
debugKit conflict

### ISSUE THREAD

**Issue by maxmasetti** [burzum/cakephp-user-tools#38] opened 2016-09-04 21:33 UTC
after installing user-tools, debugKit shows a strange behavior lacking  some (or all) view variables (path, cake, app, plugins, params and content) but only when loading user-related pages. no problems in other cases.
any hint?
thanks

**Comment by burzum** [comment] 2016-09-05 22:19
No, it just works fine in three projects on my local machine. Check if it's something in your beforeRender() or beforeFilter(). I'm pretty sure this is not related to the plugin. Also you *must* show some code, it is *impossible* to get any idea about such a problem with code!

**Comment by burzum** [comment] 2016-09-08 18:08
I'm closing this but will re-open it if you can provide details.

**Closed by burzum** 2016-09-08 18:08 UTC
Labels: bug, works for me

**Comment by matibaski** [comment] 2018-09-04 20:37
Having the same error. None of my view variables are working (seem like undefined). See screenshot of example (`groups` table with standard model, controller and templates - _I did not modify them yet_).

<img width="972" src="https://user-images.githubusercontent.com/2587920/45056288-b9940700-b092-11e8-8cbc-00de1c695b0c.png">

When I deactivate your Component in `AppController`, my page works fine:

<img width="858" src="https://user-images.githubusercontent.com/2587920/45056301-c6b0f600-b092-11e8-9049-c5acc8b4462a.png">

Also the same with the DebugKit (_like @maxmasetti told above_). Here are two screenshots of DebugKit (Deprecations and Session):

<img width="1200" src="https://user-images.githubusercontent.com/2587920/45056394-0b3c9180-b093-11e8-9672-bf7002c98bbf.png">
<img width="1192" src="https://user-images.githubusercontent.com/2587920/45056395-0b3c9180-b093-11e8-8e6b-09158a73b7a4.png">

**Comment by burzum** [comment] 2018-09-21 09:26
@matibaski I can't reproduce this. 😢 Without being able to reproduce it it's really hard to fix this. The plugin doesn't even use some of the vars that show notices.
